CREATE TABLE posts (
    -- BY DEFAULT so importers can keep post IDs from another booru. After
    -- inserting explicit IDs, advance the sequence past the highest one.
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uploader_id bigint REFERENCES users (id) ON DELETE SET NULL,
    -- general, sensitive, questionable, explicit.
    rating text NOT NULL CHECK (rating IN ('g', 's', 'q', 'e')),
    -- Check constraints rather than Postgres enums, as for users.status:
    -- values can be added or removed in a plain migration.
    status text NOT NULL DEFAULT 'active' CHECK (status IN ('pending', 'active', 'flagged', 'deleted')),
    source text NOT NULL DEFAULT '' CHECK (length(source) <= 2048),
    description text NOT NULL DEFAULT '' CHECK (length(description) <= 20000),
    parent_id bigint REFERENCES posts (id) ON DELETE SET NULL CHECK (parent_id <> id),
    score integer NOT NULL DEFAULT 0,
    fav_count integer NOT NULL DEFAULT 0,
    -- Tag search runs on this array (intarray operators @>, &&).
    tag_ids integer[] NOT NULL DEFAULT '{}',
    tag_count integer GENERATED ALWAYS AS (cardinality(tag_ids)) STORED,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX posts_tag_ids_idx ON posts USING gin (tag_ids gin__int_ops);

-- Sort orders; id breaks ties so keyset pagination is stable.
CREATE INDEX posts_score_idx ON posts (score DESC, id DESC);
CREATE INDEX posts_fav_count_idx ON posts (fav_count DESC, id DESC);
CREATE INDEX posts_created_at_idx ON posts (created_at DESC, id DESC);

CREATE INDEX posts_uploader_id_idx ON posts (uploader_id, id DESC);
CREATE INDEX posts_parent_id_idx ON posts (parent_id) WHERE parent_id IS NOT NULL;
-- Moderation queues: the few posts that are not active.
CREATE INDEX posts_status_idx ON posts (status, id DESC) WHERE status <> 'active';
