-- Comments on posts. Deleting one hides it (from everyone but staff)
-- rather than removing the row, so replies quoting it still make sense.
CREATE TABLE comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id bigint NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
    creator_id bigint REFERENCES users (id) ON DELETE SET NULL,
    -- moekura_core::markup; the web layer's comments::MAX_LEN is the real
    -- limit.
    body text NOT NULL CHECK (length(body) BETWEEN 1 AND 20000),
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    -- Set when the text is edited.
    edited_at timestamptz
);

CREATE INDEX comments_post_id_idx ON comments (post_id, id);
CREATE INDEX comments_creator_id_idx ON comments (creator_id, id DESC) WHERE creator_id IS NOT NULL;
-- The site's recent comments.
CREATE INDEX comments_recent_idx ON comments (id DESC) WHERE NOT is_deleted;

-- Visible comments only, like Danbooru's comment_count.
ALTER TABLE posts
    ADD COLUMN comment_count integer NOT NULL DEFAULT 0,
    ADD COLUMN last_commented_at timestamptz;

-- order:comment.
CREATE INDEX posts_last_commented_at_idx ON posts (last_commented_at DESC, id DESC)
    WHERE last_commented_at IS NOT NULL;

-- posts.comment_count and last_commented_at follow the visible comments.
CREATE FUNCTION comments_count() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    change integer := 0;
    post bigint;
BEGIN
    IF TG_OP = 'INSERT' THEN
        post := NEW.post_id;
        IF NOT NEW.is_deleted THEN
            UPDATE posts SET comment_count = comment_count + 1,
                             last_commented_at = GREATEST(last_commented_at, NEW.created_at)
            WHERE id = post;
        END IF;
        RETURN NULL;
    ELSIF TG_OP = 'DELETE' THEN
        post := OLD.post_id;
        change := CASE WHEN OLD.is_deleted THEN 0 ELSE -1 END;
    ELSE
        post := NEW.post_id;
        change := (CASE WHEN NEW.is_deleted THEN 0 ELSE 1 END)
                - (CASE WHEN OLD.is_deleted THEN 0 ELSE 1 END);
    END IF;
    IF change <> 0 THEN
        UPDATE posts SET comment_count = comment_count + change,
                         last_commented_at = (SELECT max(c.created_at) FROM comments c
                                              WHERE c.post_id = post AND NOT c.is_deleted)
        WHERE id = post;
    END IF;
    RETURN NULL;
END
$$;

CREATE TRIGGER comments_count
    AFTER INSERT OR DELETE OR UPDATE OF is_deleted ON comments
    FOR EACH ROW EXECUTE FUNCTION comments_count();
