-- Pools: ordered collections of posts, for comics and series
-- (`series`) or loose groups (`collection`).
CREATE TABLE pools (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- moekura_core::pools::PoolName: spaces as underscores, case kept.
    name text NOT NULL CHECK (length(name) BETWEEN 1 AND 170),
    -- moekura_core::markup.
    description text NOT NULL DEFAULT '' CHECK (length(description) <= 50000),
    category text NOT NULL DEFAULT 'series' CHECK (category IN ('series', 'collection')),
    is_deleted boolean NOT NULL DEFAULT false,
    -- The latest entry in pool_versions.
    version integer NOT NULL DEFAULT 1,
    updater_id bigint REFERENCES users (id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- Names are unique regardless of case.
CREATE UNIQUE INDEX pools_name_idx ON pools (lower(name));
-- Name searches (prefix and wildcard).
CREATE INDEX pools_name_pattern_idx ON pools (lower(name) text_pattern_ops);
CREATE INDEX pools_updated_at_idx ON pools (updated_at DESC, id DESC);

-- A pool's posts, in order. Rewritten whole when the pool is saved.
CREATE TABLE pool_posts (
    pool_id integer NOT NULL REFERENCES pools (id) ON DELETE CASCADE,
    post_id bigint NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
    -- 0-based.
    position integer NOT NULL,
    PRIMARY KEY (pool_id, post_id)
);

CREATE INDEX pool_posts_order_idx ON pool_posts (pool_id, position);
-- The pools a post is in (post pages, `pool:any`).
CREATE INDEX pool_posts_post_id_idx ON pool_posts (post_id);

-- Every saved state of every pool, for history and reverting.
CREATE TABLE pool_versions (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    pool_id integer NOT NULL REFERENCES pools (id) ON DELETE CASCADE,
    version integer NOT NULL,
    updater_id bigint REFERENCES users (id) ON DELETE SET NULL,
    name text NOT NULL,
    description text NOT NULL,
    category text NOT NULL,
    is_deleted boolean NOT NULL,
    post_ids bigint[] NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (pool_id, version)
);

CREATE INDEX pool_versions_updater_id_idx ON pool_versions (updater_id, id DESC)
    WHERE updater_id IS NOT NULL;

-- The new edit_pools permission (bit 19) for every built-in role that can
-- edit posts, as SystemRole::default_permissions has it.
UPDATE roles SET permissions = permissions | (1::bigint << 19)
WHERE system_key IN ('member', 'contributor', 'janitor', 'moderator');
