-- Notes: boxes on a post's image with text, usually translations. The box
-- is in the original file's pixels, whatever size the image is shown at.
CREATE TABLE notes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id bigint NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
    x integer NOT NULL CHECK (x >= 0),
    y integer NOT NULL CHECK (y >= 0),
    width integer NOT NULL CHECK (width > 0),
    height integer NOT NULL CHECK (height > 0),
    -- moekura_core::markup; moekura_core::notes::MAX_LEN is the real limit.
    body text NOT NULL CHECK (length(body) BETWEEN 1 AND 20000),
    -- Deleted notes stay, inactive, so they can be restored from history.
    is_active boolean NOT NULL DEFAULT true,
    -- The latest entry in note_versions.
    version integer NOT NULL DEFAULT 1,
    creator_id bigint REFERENCES users (id) ON DELETE SET NULL,
    updater_id bigint REFERENCES users (id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX notes_post_id_idx ON notes (post_id, id);
-- note:<text>.
CREATE INDEX notes_body_idx ON notes USING gin (to_tsvector('simple', body)) WHERE is_active;

-- Every saved state of every note.
CREATE TABLE note_versions (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    note_id bigint NOT NULL REFERENCES notes (id) ON DELETE CASCADE,
    post_id bigint NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
    version integer NOT NULL,
    updater_id bigint REFERENCES users (id) ON DELETE SET NULL,
    x integer NOT NULL,
    y integer NOT NULL,
    width integer NOT NULL,
    height integer NOT NULL,
    body text NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (note_id, version)
);

CREATE INDEX note_versions_post_id_idx ON note_versions (post_id, id DESC);
CREATE INDEX note_versions_updater_id_idx ON note_versions (updater_id, id DESC)
    WHERE updater_id IS NOT NULL;

-- Active notes only.
ALTER TABLE posts
    ADD COLUMN note_count integer NOT NULL DEFAULT 0,
    ADD COLUMN last_noted_at timestamptz;

-- order:note.
CREATE INDEX posts_last_noted_at_idx ON posts (last_noted_at DESC, id DESC)
    WHERE last_noted_at IS NOT NULL;

-- posts.note_count follows the active notes; last_noted_at is the last
-- time any note on the post was changed.
CREATE FUNCTION notes_count() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    change integer := 0;
BEGIN
    IF TG_OP = 'INSERT' THEN
        change := CASE WHEN NEW.is_active THEN 1 ELSE 0 END;
    ELSIF TG_OP = 'DELETE' THEN
        change := CASE WHEN OLD.is_active THEN -1 ELSE 0 END;
    ELSE
        change := (CASE WHEN NEW.is_active THEN 1 ELSE 0 END)
                - (CASE WHEN OLD.is_active THEN 1 ELSE 0 END);
    END IF;
    IF TG_OP = 'DELETE' THEN
        UPDATE posts SET note_count = note_count + change WHERE id = OLD.post_id;
    ELSE
        UPDATE posts SET note_count = note_count + change,
                         last_noted_at = GREATEST(last_noted_at, NEW.updated_at)
        WHERE id = NEW.post_id;
    END IF;
    RETURN NULL;
END
$$;

CREATE TRIGGER notes_count
    AFTER INSERT OR DELETE OR UPDATE ON notes
    FOR EACH ROW EXECUTE FUNCTION notes_count();

-- The new edit_notes permission (bit 20) for the built-in roles that can
-- edit posts, as SystemRole::default_permissions has it.
UPDATE roles SET permissions = permissions | (1::bigint << 20)
WHERE system_key IN ('member', 'contributor', 'janitor', 'moderator');
