[package]
name = "moekura"
description = "A self-hostable booru, from private instances to millions of posts"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
moekura-core.workspace = true
moekura-db.workspace = true
moekura-jobs.workspace = true
moekura-media.workspace = true
moekura-storage.workspace = true
moekura-web.workspace = true
anyhow.workspace = true
clap.workspace = true
figment.workspace = true
rpassword.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true
tokio-util.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
figment = { workspace = true, features = ["test"] }

[lints]
workspace = true
