[package]
name = "uwuu-jobs"
description = "Background job workers for uwuubooru"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
uwuu-core.workspace = true
uwuu-db.workspace = true
serde_json.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util = { workspace = true, features = ["rt"] }
tracing.workspace = true

[dev-dependencies]
serde.workspace = true

[lints]
workspace = true
