// Search metatags and their fixed values, mirroring moekura_core::search.
// A Rust test (crates/web/src/tags.rs) checks every metatag and order
// name appears here.

export const METATAGS: Readonly<Record<string, readonly string[]>> = {
  id: [],
  rating: ["general", "sensitive", "questionable", "explicit"],
  status: ["pending", "active", "flagged", "deleted", "modqueue", "unmoderated", "appealed", "any"],
  user: [],
  score: [],
  favcount: [],
  commentcount: [],
  notecount: [],
  note: [],
  width: [],
  height: [],
  mpixels: [],
  ratio: [],
  filesize: [],
  duration: [],
  date: [],
  filetype: ["jpg", "png", "gif", "webp", "avif", "jxl", "mp4", "webm"],
  md5: [],
  parent: ["none", "any"],
  tagcount: [],
  order: [
    "id",
    "id_asc",
    "score",
    "score_asc",
    "favcount",
    "favcount_asc",
    "mpixels",
    "mpixels_asc",
    "filesize",
    "filesize_asc",
    "landscape",
    "portrait",
    "duration",
    "duration_asc",
    "tagcount",
    "tagcount_asc",
    "gentags",
    "arttags",
    "copytags",
    "chartags",
    "metatags",
    "random",
    "comment",
    "comment_asc",
    "note",
    "note_asc",
    "rank",
    "change",
    "change_asc",
    "upvotes",
    "upvotes_asc",
    "downvotes",
    "downvotes_asc",
    "comment_bumped",
    "comment_bumped_asc",
    "comment_count",
    "comment_count_asc",
    "note_count",
    "note_count_asc",
    "custom",
    "md5",
    "md5_asc",
  ],
  limit: [],
  fav: [],
  ordfav: [],
  similar: [],
  pool: ["any", "none"],
  ordpool: [],
  search: ["all"],
  favgroup: ["any", "none"],
  ordfavgroup: [],
  ai: [],
  child: ["any", "none"],
  is: [
    "parent",
    "child",
    "sfw",
    "nsfw",
    "general",
    "sensitive",
    "questionable",
    "explicit",
    "pending",
    "active",
    "flagged",
    "deleted",
    "modqueue",
    "unmoderated",
    "appealed",
  ],
  source: ["any", "none"],
  approver: ["any", "none"],
  commenter: [],
  comment: [],
  noter: [],
  flagger: [],
  gentags: [],
  arttags: [],
  copytags: [],
  chartags: [],
  metatags: [],
  age: [],
  updated: [],
  upvote: [],
  downvote: [],
  has: ["source", "children", "parent", "pools", "notes", "comments"],
};

/// Prefixes that set a new tag's category when tagging.
export const CATEGORIES: readonly string[] = ["artist", "copyright", "character", "general", "meta"];
