[book]
title = "Moekura"
description = "Running, administering and using Moekura, a self-hostable booru."
authors = ["Moekura contributors"]
language = "en"
src = "src"

[output.html]
git-repository-url = "https://github.com/uwuumoe/moekura"
edit-url-template = "https://github.com/uwuumoe/moekura/edit/main/docs/{path}"
default-theme = "light"
preferred-dark-theme = "navy"
